version: "3.9"
services:
  airism:
    build: 
      dockerfile: Dockerfile
    network_mode: host
    command: /bin/bash -c "source ~/catkin_ws/devel/setup.bash && \
      source /AirSim/ros/devel/setup.bash && \
      roslaunch --wait airsim_ros_pkgs airsim_node.launch"
  avoidance:
    build: 
      dockerfile: Dockerfile
    network_mode: host
    command: /bin/bash -c "source /catkin_ws/devel/setup.bash && \
      roslaunch --wait local_planner local_planner_hitl_airsim.launch"
  rviz:
    build: 
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - avoidance
    environment:
      - LIBGL_ALWAYS_INDIRECT=$LIBGL_ALWAYS_INDIRECT
      - DISPLAY=$DISPLAY
    command: /bin/bash -c "source /catkin_ws/devel/setup.bash && \
      roslaunch --wait airsim_ros_pkgs rviz.launch"
