version: "3.9"
services:
  core:
    build: 
      dockerfile: Dockerfile
    network_mode: host
    command: roscore
  mavros:
    build: 
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - core
    command: roslaunch --wait mavros px4.launch fcu_url:=$RPI_CONNECT
  graph:
    build: 
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - LIBGL_ALWAYS_INDIRECT=$LIBGL_ALWAYS_INDIRECT
      - DISPLAY=$DISPLAY
    depends_on:
      - core
    command: rqt
  offboard_control:
    build: 
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - core
      - mavros
    command: /bin/bash -c 'source ~/catkin_ws/devel/setup.bash && roslaunch --wait app app.launch'
